In [93]:
import pandas as pd
import numpy as np

# Data visualisation
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report, accuracy_score,confusion_matrix
#load diabetes dataset from OpenML
#https://www.openml.org/d/37
#Pima Indians Diabetes Database
from sklearn.datasets import fetch_openml
diabetes = fetch_openml(name='diabetes',  as_frame=True)


/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:301: UserWarning: Multiple active versions of the dataset matching the name diabetes exist. Versions may be fundamentally different, returning version 1.
  warn(
/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


# New Section

In [3]:
## Check the data head
print(diabetes.frame.head)

<bound method NDFrame.head of      preg   plas  pres  skin   insu  mass   pedi   age            class
0     6.0  148.0  72.0  35.0    0.0  33.6  0.627  50.0  tested_positive
1     1.0   85.0  66.0  29.0    0.0  26.6  0.351  31.0  tested_negative
2     8.0  183.0  64.0   0.0    0.0  23.3  0.672  32.0  tested_positive
3     1.0   89.0  66.0  23.0   94.0  28.1  0.167  21.0  tested_negative
4     0.0  137.0  40.0  35.0  168.0  43.1  2.288  33.0  tested_positive
..    ...    ...   ...   ...    ...   ...    ...   ...              ...
763  10.0  101.0  76.0  48.0  180.0  32.9  0.171  63.0  tested_negative
764   2.0  122.0  70.0  27.0    0.0  36.8  0.340  27.0  tested_negative
765   5.0  121.0  72.0  23.0  112.0  26.2  0.245  30.0  tested_negative
766   1.0  126.0  60.0   0.0    0.0  30.1  0.349  47.0  tested_positive
767   1.0   93.0  70.0  31.0    0.0  30.4  0.315  23.0  tested_negative

[768 rows x 9 columns]>


In [4]:
## print data columns
print(diabetes.frame.columns)

Index(['preg', 'plas', 'pres', 'skin', 'insu', 'mass', 'pedi', 'age', 'class'], dtype='object')


In [5]:
## print stastiscal analysis of our data

print(diabetes.frame.describe())

             preg        plas        pres        skin        insu        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age  
count  768.000000  768.000000  
mean     0.471876   33.240885  
std      0.331329   11.760232  
min      0.078000   21.000000  
25%      0.243750   24.000000  
50%      0.372500   29.000000  
75%      0.626250   41.000000  
max      2.420

In [6]:
### print details odf data to get more insight
print(diabetes.details)

{'id': '37', 'name': 'diabetes', 'version': '1', 'description_version': '1', 'format': 'ARFF', 'creator': 'Peter D. Turney', 'collection_date': '1995-03-01', 'upload_date': '2014-04-06T23:22:13', 'language': 'English', 'licence': 'Public', 'url': 'https://api.openml.org/data/v1/download/37/diabetes.arff', 'parquet_url': 'http://openml1.win.tue.nl/dataset37/dataset_37.pq', 'file_id': '37', 'default_target_attribute': 'class', 'version_label': '1', 'citation': 'https://www.jair.org/index.php/jair/article/view/10129', 'tag': ['mythbusting_1', 'OpenML-CC18', 'OpenML100', 'study_1', 'study_123', 'study_135', 'study_14', 'study_15', 'study_20', 'study_29', 'study_30', 'study_34', 'study_37', 'study_41', 'study_52', 'study_7', 'study_70', 'study_98', 'study_99', 'uci'], 'visibility': 'public', 'original_data_url': 'https://archive.ics.uci.edu/ml/datasets/pima+indians+diabetes', 'paper_url': 'https://www.jair.org/index.php/jair/article/view/10129', 'minio_url': 'http://openml1.win.tue.nl/datas

This Python code loads the diabetes dataset from OpenML using fetch_openml() from scikit-learn. The data has 8 columns with datatype object and with no missing values. The describe () here return the description of our data frame. It sets the parameter as_frame=True to load the data as a panda DataFrame.

In [20]:
## lets looks into data types

print(diabetes.frame.dtypes)

preg      float64
plas      float64
pres      float64
skin      float64
insu      float64
mass      float64
pedi      float64
age       float64
class    category
dtype: object


In [21]:
## Before going any further, check if there are  null values in the data 

print(diabetes.frame.isnull)

<bound method DataFrame.isnull of      preg   plas  pres  skin   insu  mass   pedi   age            class
0     6.0  148.0  72.0  35.0    0.0  33.6  0.627  50.0  tested_positive
1     1.0   85.0  66.0  29.0    0.0  26.6  0.351  31.0  tested_negative
2     8.0  183.0  64.0   0.0    0.0  23.3  0.672  32.0  tested_positive
3     1.0   89.0  66.0  23.0   94.0  28.1  0.167  21.0  tested_negative
4     0.0  137.0  40.0  35.0  168.0  43.1  2.288  33.0  tested_positive
..    ...    ...   ...   ...    ...   ...    ...   ...              ...
763  10.0  101.0  76.0  48.0  180.0  32.9  0.171  63.0  tested_negative
764   2.0  122.0  70.0  27.0    0.0  36.8  0.340  27.0  tested_negative
765   5.0  121.0  72.0  23.0  112.0  26.2  0.245  30.0  tested_negative
766   1.0  126.0  60.0   0.0    0.0  30.1  0.349  47.0  tested_positive
767   1.0   93.0  70.0  31.0    0.0  30.4  0.315  23.0  tested_negative

[768 rows x 9 columns]>


there is not null values in our data

We have only one categorical data which is class

 Encoding ordinal variable
The only ordinal variable in our dataset is the class of education feature.

In [54]:
### define our x imput and y output

x = diabetes.frame.drop('class', axis = 1)
y = diabetes.frame['class']

In [55]:

# Instantiate LabelEncoder
class_le= LabelEncoder()


In [56]:
# Apply LabelEncoder to the class column 
x= class_le.fit_transform(diabetes.frame['class'].values)




In [57]:
## print x
x

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [76]:

# Instantiate OneHotEncoder

ohe = OneHotEncoder()

In [89]:
# Apply OneHotEncoder to the class column 

ohe.fit_transform(diabetes.frame[['class']])[:5]

<5x2 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [90]:
# The first 5 rows the class column for comparison

diabetes.frame['class'].head()

0    tested_positive
1    tested_negative
2    tested_positive
3    tested_negative
4    tested_positive
Name: class, dtype: category
Categories (2, object): ['tested_negative', 'tested_positive']

In [79]:
# class categories in OneHotEncoder 

ohe.categories_

[array(['tested_negative', 'tested_positive'], dtype=object)]

Partion dataset into separate training and test datasets


In [80]:


# Train test split 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [81]:
### print data shape
print("X_train shape: ", x_train.shape)
print("Y_train shape: ", y_train.shape)
print("X_test shape: ", x_test.shape)
print("Y_test shape: ", y_test.shape)

X_train shape:  (537, 8)
Y_train shape:  (537,)
X_test shape:  (231, 8)
Y_test shape:  (231,)


In [102]:
### Instantiate pipeline testing with SVM

svm_model = svm.SVC(decision_function_shape='ovo')
svm_model.fit(x_train, y_train)

#we predict the test set
predict_test = svm_model.predict(x_test)




In [105]:
#we predict the test set with rbf kermel and ovo decision
predict_test = svm_model.predict(x_test)
y_pred = svm_model.predict(x_test)
print("Accuracy score with rbf kernel and ovo decision_function_shape: ", accuracy_score(y_test, y_pred))


Accuracy score with rbf kernel and ovo decision_function_shape:  0.7359307359307359


In [97]:
## predict decison test with poly kernel and ovo decision

svm_model = svm.SVC(kernel='poly', decision_function_shape='ovo')
svm_model.fit(x_train, y_train)
y_pred = svm_model.predict(x_test)
print("Accuracy score with poly kernel and ovo decision_function_shape: ", accuracy_score(y_test, y_pred))


Accuracy score with poly kernel and ovo decision_function_shape:  0.7489177489177489


In [106]:
### with linear kernel and ovo decision
svm_model = svm.SVC(kernel='linear', decision_function_shape='ovo')
svm_model.fit(x_train, y_train)
y_pred = svm_model.predict(x_test)
print("Accuracy score with linear kernel and ovo decision_function_shape: ", accuracy_score(y_test, y_pred))



Accuracy score with linear kernel and ovo decision_function_shape:  0.7445887445887446


In [107]:
# Fit SVM model with ovr decision function shape
svm_model = svm.SVC(kernel='linear', decision_function_shape='ovr')
svm_model.fit(x_train, y_train)
y_pred = svm_model.predict(x_test)
print("Accuracy score with linear kernel and ovr decision_function_shape: ", accuracy_score(y_test, y_pred))

Accuracy score with linear kernel and ovr decision_function_shape:  0.7445887445887446


In [108]:
#### fit with rbf

svm_model = svm.SVC(kernel='rbf', decision_function_shape='ovr')
svm_model.fit(x_train, y_train)
y_pred = svm_model.predict(x_test)
print("Accuracy score with rbf kernel and ovr decision_function_shape: ", accuracy_score(y_test, y_pred))


Accuracy score with rbf kernel and ovr decision_function_shape:  0.7359307359307359


In [111]:
##### print training accuracy with svm model and ovo decision _function_shape

svm_model = svm.SVC(decision_function_shape='ovo')
svm_model.fit(x_train, y_train)

svm_model = svm.SVC(decision_function_shape='ovo')
svm_model.fit(x_train, y_train)

### we need predict train set

predict_train= svm_model.predict(x_train)

### we need predict test

predict_test=svm_model.predict(x_test)



from sklearn.metrics import classification_report,confusion_matrix

print('Training accuracy')

#we report the confusion matrix for the training set

print(confusion_matrix(y_train, predict_train))
#we report various accuracy statistics for the training set
print(classification_report(y_train, predict_train))

print('Testing accuracy')
#we report the confusion matrix for the test set
print(confusion_matrix(y_test,predict_test))
#we report various accuracy statistics for the test set
print(classification_report(y_test,predict_test))

Training accuracy
[[326  23]
 [ 95  93]]
                 precision    recall  f1-score   support

tested_negative       0.77      0.93      0.85       349
tested_positive       0.80      0.49      0.61       188

       accuracy                           0.78       537
      macro avg       0.79      0.71      0.73       537
   weighted avg       0.78      0.78      0.76       537

Testing accuracy
[[131  20]
 [ 41  39]]
                 precision    recall  f1-score   support

tested_negative       0.76      0.87      0.81       151
tested_positive       0.66      0.49      0.56        80

       accuracy                           0.74       231
      macro avg       0.71      0.68      0.69       231
   weighted avg       0.73      0.74      0.72       231

